[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "slurmtool"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.82.0,<1.83"
python = "==3.12"
rich = ">=13.9.4,<14"
click = ">=8.1.7,<9"
structlog = ">=24.4.0,<25"
pandas = ">=2.2.3,<3"


[system-requirements]
linux="3.10.0"
libc="2.17"
